### ISSUE TITLE
Accessibility focus management

### ISSUE THREAD

**Issue by kryp71c** [osano/cookieconsent#350]
Asides from the inability to trigger the dismiss button by keyboard (issues https://github.com/insites/cookieconsent/pull/213 and https://github.com/insites/cookieconsent/issues/249), the focus management should be addressed.

According to the dialog design pattern, focus should be on an element inside the dialog modal when it is first opened, and return to the invoking element when closed (see [here](https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/#dialog_modal) and [here](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_dialog_role)).

Since there is no invoking element in this case, focus should likely be returned to where it was when the dialog first opened (if any) or the top of the page.

There is a workaround by using the supplied function hooks and doing something like this:
```js
"onPopupOpen": function() {
  // Store currently active element in custom global.
  window.cookieconsent.ccFocus = document.activeElement;

  // Set the focus to the dismiss button.
  document.getElementsByClassName('cc-dismiss')[0].focus();
},
"onPopupClose": function() {
  // If there was no previously focused element remove the current focus,
  // otherwise set focus to previous element.
  if (window.cookieconsent.ccFocus === document.body) {
    document.activeElement.blur();
  }
  else {
    window.cookieconsent.ccFocus.focus();
  }
},
```
The current implementation has an aria-live attribute, which will read out the content but won't actually enable users to easily move to the action items. This is especially true, if the user has already moved the focus inside the document when the cookie dialog is opened.

Therefore, setting the focus on an element in the dialog when it is opened would enable users to quickly move to the action buttons, thereafter returning to their previous position. The aria-live attribute should then be removed, since the aria-label and aria-described by attributes on the dialog window should already announce the content.

**Comment by alexmorleyfinch** [comment]
This is a great suggestion, we'll be sure to add focussing to the next release!
