### ISSUE TITLE
Expiration date issue

### ISSUE THREAD

**Issue by Vorosfej** [osano/cookieconsent#385]
Hi!
I want to set the expiration time for a single session. I tried zero in the script.js file, but it does not work. If I click on the accept button, the warning disappears but will not reappear after the next opening of the website, unless I have previously deleted the browser cache. I would like to ask for help in solving this.
The js code looks like this:

```js
var g = {
    enabled: !0,
    container: null,
    cookie: {
        name: "cookieconsent_status",
        path: "/",
        domain: "",
        expiryDays: 0
    },
}
```

I'm sorry, but my English knowledge is poor and I used a google translator. I hope the problem is understandable.

Regards!

**Comment by jakefuller1** [comment]
To create a session cookie, do not specify Expires directive. However, web browsers may use session restoring, which makes most session cookies permanent, as if the browser was never closed.
cookieconsent may set default expires to 365 days?

**Comment by Vorosfej** [comment]
Thanks for the quick response.

Do you think that?

            setCookie: function(e, t, i, n, o) {
                var s = new Date;
                s.setDate(s.getDate() + (i || 365));
                var r = [e + "=" + t, "expires=" + s.toUTCString(), "path=" + (o || "/")];
                n && r.push("domain=" + n), document.cookie = r.join(";")
            },

Then there is this from which I tried to delete the expiryDays line, but it was not good either.

            var g = {
                enabled: !0,
                container: null,
                cookie: {
                    name: "cookieconsent_status",
                    path: "/",
                    domain: "",
                    expiryDays: 0
                },

Or should I set 365 days elsewhere?

**Comment by jakefuller1** [comment]
Not sure why you would want to set cookie consent to session cookie?

As it is even with location, I can see many problems. If your IP is in Europe, does not make you an European citizen (i.e. foreign diplomats, temporary workers, migrants, visitors, US military, etc.) If you do not log in, give name & address, I could see other problems. If a family of 4 shares computer, who consented? Is he/she of legal age to consent? Did you ask age? In a hotel or library, who consented?

What about cookies set before May 25, are they grandfathered in? Who should delete these, user or us?

Unless the EU lets us query a database of its citizens, address and age, I am not sure there is a foolproof way to implement cookie law.

I would try: (not tested)
 setCookie: function(e, t, i, n, o) {
            var r = [e + "=" + t, "path=" + (o || "/")];
            n && r.push("domain=" + n), document.cookie = r.join(";")
        },

var g = {
            enabled: !0,
            container: null,
            cookie: {
                name: "cookieconsent_status",
                path: "/",
            },

As I said before, the browser may still use session restoring. Unless you have a very good reason, I would leave cookie consent at 365 days. Less annoying to website visitors.

**Comment by Vorosfej** [comment]
You may be right, I still think about it. Thanks for your help.

**Comment by alexmorleyfinch** [comment]
Hmm, when you set the value to 0, could you check the `expire` time on the cookie itself? If you are using Chrome you can open the developer tools and go to `Application`. You can see all the cookies and info. Check the `expire` time of the cookie that you just set. Is it in the past?

I think this may be a weird browser quirk, seeing as you are setting the expire time very close to the current time. What happens if you set expire to 1? (although annoyingly you'll have to wait a day to see if the cookie actually expires on it's own.)
