### ISSUE TITLE
Cookie is ignored, when Cookie for "/" on same domain exists

### ISSUE THREAD

**Issue by seeeeew** [osano/cookieconsent#404]
I'm running multiple sites on the same domain. The cookies for different paths don't interfere with each other, but as soon as the cookie for the path "/" exists, the cookies for all other paths are ignored.

**Comment by InsanityMeetsHH** [comment]
Take a look at [Cookie Options](https://cookieconsent.insites.com/documentation/javascript-api/#cookie_options) to set a custom path for each site.

**Comment by seeeeew** [comment]
I did. Sorry if that wasn't clear from my original comment.

I set `cookie.path` to the correct value for each path (including "/"), but as soon as the cookie for the path "/" exists, the cookies for all other paths are ignored.

**Comment by InsanityMeetsHH** [comment]
You could also set a custom `cookie.name` for each site.

**Comment by alexmorleyfinch** [comment]
Let me just clarify, if you set a cookie with a path of "/", then any other cookie (with the same name on a different path) will get ignored.

I think this is an issue with cookies in general, and not specific to our tool (although I may be mistaken).

You could take a look at the solution offered [here](https://stackoverflow.com/questions/8406719/cookies-set-across-multiple-domains) and see if that works. It's a bit of work though.
