### ISSUE TITLE
Can't change dismiss text

### ISSUE THREAD

**Issue by Soph87** [osano/cookieconsent#420]
Hi! 
I'm using cookie consent for my website, and it seems that when I check "Let users opt out of cookies ", I can't change the dismiss text which is automatically set to "allow cookies" .
I on't know if it's a bug or me not using it the right way...
Thanks!

**Comment by pklinke** [comment]
Same problem, seems to be new

**Comment by Luckyfella73** [comment]
I just had the same issue. The only way to fix it for me was loading an older version of cookiesonsent. I just took the resources from a project I did a few month ago:

`<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css" />
	<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>`

So it looks like the translation issue is a bug - I hope it can be fixed soon - it's allways nicer to load the newes version though the "bit older one" works pretty fine as well :)

**Comment by circleart** [comment]
Same problem in currently used version 3.1.0.
This error only occurs after I have changed the type to "opt-out".

**Comment by stefanroehrbein** [comment]
Try
```javascript
...
  "deny": "Dismiss this!",
...
```
instead of
```javascript
...
  "dismiss": "Dismiss this!",
...
```
Works for me with current version (3.1.0).
They should update their "Download" section - wrong here as well :(

**Comment by Luckyfella73** [comment]
When I get the code right **_dismiss_** and **_deny_** are more or less oposite. **_Dismiss_** is what you click to say "ok I got it, go on dear website" and **_deny_** means "I don't accept cookies and refuse to use them".

**Comment by StudioVDS** [comment]
Just change dismiss to allow and it should work fine:
`"allow": "Allow cookies",`

**Comment by Larsinholo** [comment]
Hey @Luckyfella73 thx,

I did not publish the container ;-( and indeed it works fine with the deny. Sorry for asking my bad. 

Thank you!

**Comment by Luckyfella73** [comment]
@Larsinholo 
> ... and indeed it works fine with the deny
> 
> Thank you!

You are welcome - nice you got it to work now!

**Comment by arlogilbert** [comment]
This may be a bug in the configurator, we will look into this shortly.

**Comment by relicmelex** [comment]
Configurator & Documentation both use`deny. Closing issue in respect to reply: https://github.com/osano/cookieconsent/issues/420#issuecomment-458949570
