### ISSUE TITLE
visibility issue on iphone 10 safari IOS 11.4.1

### ISSUE THREAD

**Issue by tre3141** [osano/cookieconsent#421]
when viewing the site on mobile - i phone 10 IOS 11.4.1 the user is not able to access the "got it" button. it's below the screen on the phone and you can't seem to scroll down to it. 

is anyone else having this issue? 

if so - how have you been able to resolve it?

thank you very much

-3141

**Comment by relicmelex** [comment]
@tre3141 It looks like this has to do with the text wrapping and forcing the buttons too far down. I'm been able to reproduce and when I get a chance to look into it further I will provide an update.

**Comment by relicmelex** [comment]
@tre3141 After some css trudging and realizing that the whole body was bigger than the viewport was I thought "Maybe this is something else". So the problem doesn't actually lie within the package, it has to do with setting your viewport with the correct meta tags...

Remember to put this guy in your header to force iPhones to use the correct viewport all the time:
```html
<meta
  name="viewport"
  content="user-scalable=no,width=device-width,initial-scale=1,maximum-scale=1">
```

Cheers!
