### ISSUE TITLE
Cookie Consent displaying behind ShareThis icons

### ISSUE THREAD

**Issue by itsvirtus** [osano/cookieconsent#429]
I use ShareThis to display social icons at the bottom of my pages on mobile. My issue is that Cookie Consent is displaying behind these icons, making it impossible to read the consent pop-up. Am I able to modify the z-index of Cookie Consent to make it appear in front of my ShareThis icons?

**Comment by Footprint-Addons** [comment]
I think the easiest way is that you download the css, adapt it and link to it from your own site.

**Comment by arlogilbert** [comment]
Need to update CSS to increase z-index.

**Comment by relicmelex** [comment]
@itsvirtus thank you for reporting this bug!

The root element of Cookie Consent is `9999`. We're probably going to lower this by default but provide an option in the config for changing this so it can work with any app.

For now consider changing the container element that's being used and change the z-index of that to be higher than your ShareThis container: 

```
window.cookieconsent.initialise({
  ...otherOtps,
  container: document.getElementById( "content" )
})
```

**Comment by relicmelex** [comment]
@itsvirtus I know it's been a while, but can you please post your configuration and system setup?

-EG-
Build: Mac PowerBook Circa mid 2015
OS: OSX - 10.14.5
Browser: Chrome - Version 75.0.3770.100 (Official Build) (64-bit)

Config:
```javascript
{
  container: document.getElementById("content"),
  palette:{
     popup: {background: "#fff"},
     button: {background: "#aa0000"},
  },
  revokable:true,
  onStatusChange: function(status) {
     console.log( status ? 'enable cookies' : 'disable cookies');
  },
  law: {
     regionalLaw: false,
  },
  location: true
}
```

**Comment by itsvirtus** [comment]
Hey,

I think I got this up and running how it should.

Sincerely,
Charles

____________

Charles Hoffman
Glendale, CA 91203
charlesirahoffman@gmail.com <mailto:charlesirahoffman@gmail.com>  |  +1 (818) 934-2369 <tel:+1%20(818)%20934-2369>
