### ISSUE TITLE
Reset Cookie Consent Message

### ISSUE THREAD

**Issue by bksacuesa** [osano/cookieconsent#431]
Hi dear team .Thanks for sharing this code with everyone.

I have implemented the cookie consent on my website successfully although the cookie Consent message reappears every time someone loads the site.

Anyone We can figure it out that??

Regards

**Comment by relicmelex** [comment]
@bksacuesa Firstly, let me apologize for the delayed response. Are you still having this issue? Were you clearing you cookies or using an incognito browser, because that will make it show back up even after you have accepted or denied or any answer for that matter.

**Comment by relicmelex** [comment]
Stale. Closing issue. If this comes back up please open a new issue in the 'bug' category as it will ask you for more detail to help us better resolve the issue.
