### ISSUE TITLE
Question about revocation after 1st Acceptance

### ISSUE THREAD

**Issue by roygrubb** [osano/cookieconsent#434]
I have installed cookieconsent and it works well.  Thank you for making this useful script available to all.

I have just one issue: The "Cookie Policy" tab that drops down when the user accepts cookies (cc-revoke) only appears once.  If I accept cookies and then reload the page it doesn't appear, so unless the user is using a cookie manager, they don't seem to have a way of revoking their acceptance of cookies after the initial acceptance.

Is this how cookieconsent is intended to work or does it indicate I've configured it wrongly?

My site can be seen [**here**](https://www.mind-mapping.org).

**Comment by emmanuel-franc** [comment]
Hi,

I'm running in the same issue. Plus, whenever I don't need the `cc-revoke` button it still appear once I accept cookies.

**Comment by arlogilbert** [comment]
Need to add a mini interface that floats on the page in bottom left or bottom right to open ability to revoke. This will be solved as part of #556

**Comment by roygrubb** [comment]
Thanks.  Will keep an eye open for #556

**Comment by relicmelex** [comment]
This is floating off-topic so I will close & lock it. As already mentioned this will be resolved in feature #556.
