### ISSUE TITLE
gulp build needs a prerequisite in the README.md

### ISSUE THREAD

**Issue by ascooper57** [osano/cookieconsent#437]
I had to do this on my Mac...
   **npm install --global gulp npm link gulp**
   gulp build

Cudo's to you. This is the best GDPR example I seen so far.

**Comment by mbuk** [comment]
@ascooper57 you do know this is not GDPR compliant right? 
See: [https://github.com/insites/cookieconsent/issues/409#issuecomment-404567026](https://github.com/insites/cookieconsent/issues/409#issuecomment-404567026) and [https://github.com/insites/cookieconsent/issues/242](https://github.com/insites/cookieconsent/issues/242)
