### ISSUE TITLE
Link to Privacy Agreement inside Message

### ISSUE THREAD

**Issue by magic-77** [osano/cookieconsent#440]
I'm using this setup to show cookie banner with a link inside message block
but i can't remove link that is set with this plugin

```
window.cookieconsent.initialise({
	palette: {
		popup: {
			background: '#ededed'
		},
		button: {
			background: '#D03E89'
		}
	},
	content: {
		message: 'text text <a href="/home/datenschutz" target="_blank">link to privacy agreement</a> text text',
		dismiss: 'Agree',
		link: null / undefined <-- not working to remove link
	}
});
```

**Comment by thexmanxyz** [comment]
@magic-77 Please take a close look on the button [markup definition](https://github.com/insites/cookieconsent/blob/master/src/cookieconsent.js#L265-L280), [layouts parameter](https://github.com/insites/cookieconsent/blob/master/src/cookieconsent.js#L265-L280) and the [actual layout](https://github.com/insites/cookieconsent/blob/master/src/cookieconsent.js#L265-L280). These are some parameters which can be used to influence the banner rendering. You can configure these parameters during plugin initialization to modify the markup of your banner.

For more information on how to do that correctly and what these parameters do please revisit my issue https://github.com/insites/cookieconsent/issues/365 which includes in deep explanations how to modify the default markup and layout(s).
