### ISSUE TITLE
Don't create a 'deny' cookie if user dismisses

### ISSUE THREAD

**Issue by loeffe1** [osano/cookieconsent#441]
Currently the script will create a cookie with value deny if the user dismisses cookies. I want to change this so no cookie is created at all in this case.

**Comment by tvladan** [comment]
The only way I could think of is of you have a mysql db with all the ip's of the machines that choose refuse and every time someone visits you page you check those against the visitor's ip. if it is in the db with refuse checked than you know their choice. That would require no cookies stored on the visitor's machine. I know of no other way in which you could check someones choice regarding cookies, other than the one setting a cookie with refuse. The mysql solutions is ludicrous of course ... and could fall under the category of collecting personal data. Also you could write a disclaimer for your visitors warning them that the "refuse" choice will set a refuse cookie on their machine, and if they want no cookies should not choose anything, that resulting in the banner brought up every time they visit the site.  Or you could re-write the code to not set a cookie when refuse is selected, that also resulting in the banner being brought up every visit.  The part that should be re written is at scr/cookieconsent.js line 48. If var value == "refuse" set var cookie=""  that should work theoretically.

**Comment by arlogilbert** [comment]
> Currently the script will create a cookie with value deny if the user dismisses cookies. I want to change this so no cookie is created at all in this case.

You would need to create custom callbacks to do this. EU laws allow for necessary cookies without any consent, even a cookie to track that cookies have been denied is legal.
