### ISSUE TITLE
cdn in cookieconsent.min.js

### ISSUE THREAD

**Issue by blueamerican** [osano/cookieconsent#443]
i link to local files, e.g. cookieconsent.min.js.

But in this file there is a cdn:

`!function(){if(!window.hasCookieConsent){window.hasCookieConsent=!0;var e="cookieconsent_options",t="update_cookieconsent_options",n="cookieconsent_dismissed",i="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.10/";`

I do not really understand this. Is ther a possibility to get rid of this cdn?

**Comment by multiformeingegno** [comment]
Interested in this as well - did anyone find a solution?
