### ISSUE TITLE
dismissOnClick breaks because of event.path usage

### ISSUE THREAD

**Issue by SlootSantos** [osano/cookieconsent#446]
As the title indicates, the _dismissOnWindowClick_ breaks in at least Safari, Firefox and IE.

This is because this very function tries to look up the property _path_ on an event object.
But since _event.path_ is non-standard it throws an error when trying to access the _length_ property assuming _event.path_ would return an array itself.

```
var onWindowClick = function(evt) {
          var isIgnored = false;
          var pathLen = evt.path.length; // RIGHT HERE
          var ignoredLen = ignoredClicks.length;
          for (var i = 0; i < pathLen; i++) {
            if (isIgnored) continue;

            for (var i2 = 0; i2 < ignoredLen; i2++) {
              if (isIgnored) continue;

              isIgnored = util.hasClass(evt.path[i], ignoredClicks[i2]); // RIGHT HERE
            }
          }

          if (!isIgnored) {
            setStatus(cc.status.dismiss);
            close(true);

            window.removeEventListener('click', onWindowClick);
            this.onWindowClick = null;
          }
        }.bind(this);
```

I already created an PR to fix this issue.
There is a standard property on the event object named composedPath.
This function returns the very same thing that the code is expecting. Namely an array of DOM elements.
 
https://github.com/insites/cookieconsent/pull/445

**Comment by schoenwaldnils** [comment]
sadly `event.path` and `event.composedPath` both are not supported in IE11 and Edge :/

**Comment by relicmelex** [comment]
There's currently a PR that's been accepted into dev that will be in the next release that fixes this. Thank you for your continued support!
