### ISSUE TITLE
Doesn't Display On Firefox

### ISSUE THREAD

**Issue by MartyD23** [osano/cookieconsent#454]
Hi,

I've noticed the cookie consent banner is no longer displaying on firefox.

Works on chrome and edge.

Is anyone else experiencing this issue?

**Comment by thexmanxyz** [comment]
@MartyD23 Nope still works on all browsers

**Comment by MemnochDaCoder** [comment]
I'm seeing the same issue.  When checking the console it's throwing an error. 

TypeError: window.cookieconsent is undefined

**Comment by MemnochDaCoder** [comment]
Well I feel silly.  There's a root CA on my work machine preventing the cloudflare js from loading that's causing the issue.
