### ISSUE TITLE
opt-in/opt-out doesn't work properly

### ISSUE THREAD

**Issue by dolav** [osano/cookieconsent#464]
First of all, thank you for this helpful project.

There is an issue with the opt-in/opt-out types- both types behave in the same way.
Step to reproduce:
1. Open the [example page](https://cookieconsent.insites.com/download/)
2. Change the type to opt-in.
3. Buttons are 'deny' and 'allow':
![opt-in](https://user-images.githubusercontent.com/41971677/46095429-85d86880-c18a-11e8-8e4f-b8ad8ef8dc08.png)
4. Change the type to opt-out.
5. Buttons are 'deny' and 'allow':
![opt-out](https://user-images.githubusercontent.com/41971677/46095675-1c0c8e80-c18b-11e8-991a-72c9c3f7d72f.png)

In general, the type values are different, but the behaviors are the same.

**Comment by thexmanxyz** [comment]
@dolav This seems to be an issue with the configurator, I can't see any issues concerning the output generation on my server when defining different `type` parameter options.

Please verify by testing it locally or on your server and report back. Also I checked the actual JS code which handles the opt-in/opt-out handling found [here](https://github.com/insites/cookieconsent/blob/master/src/cookieconsent.js#L781-L792) which seems to use the correct indices for the predefined markups.

**Comment by thexmanxyz** [comment]
@dolav I revisited the markup generation there might be a misconception on your side and probably the configurator does also work correctly. Take a look on the markup definition for `allow` and `deny` [here](https://github.com/insites/cookieconsent/blob/master/src/cookieconsent.js#L273-L276) as well as the button generation [here](https://github.com/insites/cookieconsent/blob/master/src/cookieconsent.js#L296-L302).

If you are unhappy if the output generation, feel free to override the defaults.

**Comment by dolav** [comment]
Hi @thexmanxyz,
Thanks for your answer!

I found the bug- The default compliances in the code are different than the ones you described in the [API documentation](https://cookieconsent.insites.com/documentation/javascript-api/).
[code snippet](https://github.com/insites/cookieconsent/blob/master/src/cookieconsent.js#L295):
```
// define types of 'compliance' here. '{{value}}' strings in here are linked to `elements`
compliance: {
  info: '<div class="cc-compliance">{{dismiss}}</div>',
  'opt-in':
    '<div class="cc-compliance cc-highlight">{{deny}}{{allow}}</div>',
  'opt-out':
    '<div class="cc-compliance cc-highlight">{{deny}}{{allow}}</div>'
}
```
It's probably a copy paste error.
Thanks

**Comment by thexmanxyz** [comment]
@dolav Hey, yeah you are totally right I rechecked v3.0.3 - v3.0.6.

```
"opt-in":'<div class="cc-compliance cc-highlight">{{dismiss}}{{allow}}</div>'
```

```
"opt-out":'<div class="cc-compliance cc-highlight">{{deny}}{{dismiss}}</div>'
```

It seems that this was introduced with 3.1.0. I also was to lazy to check on differences between 3.0.6 and 3.1.0 even as I thought about doing it. Neither I looked on the API -.-. Sorry. I will issue a PR in the next minutes. Thanks for helping figuring that out!

**Comment by thexmanxyz** [comment]
@davidjamartin Sorry for being a bit harsh in the first place and dismissing an actual issue :)

**Comment by thexmanxyz** [comment]
@dolav np and sorry for being a bit harsh in the first place and dismissing an actual issue :-). Simply override the parameters until they fix the API, it probably will take some time...until they merge the PR. I won't recommend rolling back to < 3.1.0 because there are a lot of fixes included.

**Comment by soxhi8** [comment]
Issue still persists. Just a minor fix update would be great, no everyone will find the error or this thread by themselves.

**Comment by thexmanxyz** [comment]
@soxhi8 The problem has already been addressed within #468, merge is still required and open.

**Comment by soxhi8** [comment]
> 
> 
> @soxhi8 The problem has already been addressed within #468, merge is still required and open.

Yes, thank you for that fix! However, as you already said it hasn’t been merged so far and it’s been a while. Do you know an active fork of the project, which is actually maintained?

**Comment by thexmanxyz** [comment]
@soxhi8 So you are in the same situation as everyone else. There is no other active fork but feel free to create one and merge the open fixes. Alternatively you can try to tag an owner and demand on merge or create your own fork which includes all the proposed fixes.

**Comment by relicmelex** [comment]
I've set the code into a PR: #569
