### ISSUE TITLE
Cookieconsent for Nextcloud?

### ISSUE THREAD

**Issue by ap2de** [osano/cookieconsent#466]
If possible I would like to have a desciption, how cookieconsent will be used together with nextcloud.
Currently I do not know, where to enbed the javascript code.
Thank you for your response.

**Comment by thexmanxyz** [comment]
@ap2de I assume that you need to modify the template or create your own. The actual cookieconsent configuration and "loading" would work the same no matter what site you want to use it on. A quick search brought up something like  [this](https://help.nextcloud.com/t/how-to-insert-own-js-files-to-adjust-theme-of-nextcloud/3473). This should help you to find more info on this topic and how you can apply your own markup to nextcloud.

**Comment by relicmelex** [comment]
@ap2de Sorry for the delayed reply. Unfortunately CookieConsent is a stand alone package and doesn't extend support into others or have any integrations. There is nothing at this time slated for that as we expect to always be able to be used with very little hassle and customization allowing the library to be used the same way in any situation. Have you tried contacting nextcloud?

-- Supported Answer --
As the [JavaScript CC API](https://cookieconsent.osano.com/documentation/javascript-api/) describes, this can go in your `index.html` file.
