### ISSUE TITLE
Move cookie consent dialog at the bottom of the body

### ISSUE THREAD

**Issue by vasilis1nakos** [osano/cookieconsent#467]
Hi, is there any way to add the cookie consent dialog div at the end of the body element before closing it so that the cookie consent dialog will not be the first element in the body?

Thank you in advance.

**Comment by thexmanxyz** [comment]
@vasilis1nakos You can do this by using the `autoAttach: false` parameter. Take also a look at the corresponding source code documentation [here](https://github.com/insites/cookieconsent/blob/master/src/cookieconsent.js#L379-L385). 

Be aware of the `.appendChild()` function which is also explained in the code docs. More info on `appendChild` [here](https://www.w3schools.com/jsref/met_node_appendchild.asp).

**Comment by jamieburchell** [comment]
The widget should "append" itself to the body by default, though? https://github.com/insites/cookieconsent/issues/498

**Comment by thexmanxyz** [comment]
@vasilis1nakos Just for the sake of completeness this will also work by simply defining your own element as the last element in the body:

```JS
window.addEventListener("load", function(){
  var node = document.createElement("div");
  document.body.appendChild(node); 
  window.cookieconsent.initialise({
    "palette": {
      "popup": {
        "background": "#000"
      },
      "button": {
        "background": "#f1d600"
      }
    },
    "container": node,
})});
``` 

and as @jamieburchell noted the `factory` method outlined in the source is not existent so you have to use `var instance = new cookieconsent.Popup(options);` to retrieve the CC instance.

**Comment by arlogilbert** [comment]
Bumping this to the top.

**Comment by thexmanxyz** [comment]
@arlogilbert See PR #499 which contains the functionality dicsussed here

**Comment by arlogilbert** [comment]
Hi @thexmanxyz - We are dedicating an engineering resource to Cookie Consent for the next few weeks and will be implementing this capability. It will be up to him to evaluate your pull request to determine whether it solves the issue, but at first glance, it does appear that your code under #499 would do the job.

Thanks for bringing this to my attention.

**Comment by thexmanxyz** [comment]
@arlogilbert Alright. I Just wanted to point to the corresponding PR because you bumped the issue ;) and I wasn't sure if it got noticed. It's up to you if it will be merged or not. But the PR should work as I tested it at the time I submitted it :).

**Comment by relicmelex** [comment]
Please see the updated documentation. This is not the library, it is order of operations and when and how you load things issue. We've updated our recommendation:

https://cookieconsent.osano.com/download/
