### ISSUE TITLE
Move "Learn more" link beside "Got it!" button

### ISSUE THREAD

**Issue by mrleemon** [osano/cookieconsent#469]
Hi,

I was wondering if it's possible to move the "Learn more" link beside the "Got it!" button.
Any help would be appreciated.

Thanks in advance

**Comment by relicmelex** [comment]
@mrleemon Sorry for the delayed reply. Are you still looking for help with this?

**Comment by mrleemon** [comment]
No, I managed to find the solution myself. Thanks, anyway!
