### ISSUE TITLE
Link to revoke choice for policy page

### ISSUE THREAD

**Issue by simonnowos** [osano/cookieconsent#472]
Hello,

i would like to have a link to add to my poliy page that has the same functionallity as the "Cookie Policy" Button that appears on the bottom of my page. So after clicking on the link the pop-up should appear again and the user can choose the option again. 

Can anyone help me?

**Comment by m4m-simon** [comment]
this is my workaround:

```javascript
document.querySelector('.cc-revoke').click();
```

**Comment by JeePeeNL** [comment]
@m4m-simon can you please explain how you add that to a link?

Thanks
JP

**Comment by m4m-simon** [comment]
This "Link" uses javascript to "click" the Revoke Button of the Cookie Consent Banner.

```html
<a href="javascript:document.querySelector('.cc-revoke').click()">My Link</a>
```

**Comment by JeePeeNL** [comment]
Cool that works. Thank you @m4m-simon !

**Comment by relicmelex** [comment]
Closing due to work around. This is not a feature the library supports officially. This is only meant to be used as the docs describe.
