### ISSUE TITLE
ipinfo responds "Unexpected token R in JSON"

### ISSUE THREAD

**Issue by DavidJMarcus** [osano/cookieconsent#475]
Chome Developer Tools shows the following errors when I go to https://www.ratingscentral.com/. This is with //cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js

cookieconsent.min.js:1 GET https://ipinfo.io/ 429
n @ cookieconsent.min.js:1
e.runService @ cookieconsent.min.js:1
e.locate @ cookieconsent.min.js:1
e.getCountryCode @ cookieconsent.min.js:1
e.initialise @ cookieconsent.min.js:1
(anonymous) @ (index):1
load (async)
(anonymous) @ (index):1

cookieconsent.min.js:1 The service[0] (//ipinfo.io) responded with the following error Error: Error [UNKNOWN]: Invalid response (SyntaxError: Unexpected token R in JSON at position 0)
    at o (cookieconsent.min.js:1)
    at Object.callback (cookieconsent.min.js:1)
    at e.runServiceCallback (cookieconsent.min.js:1)
    at cookieconsent.min.js:1
    at XMLHttpRequest.function.s.onreadystatechange (cookieconsent.min.js:1)
e.logError @ cookieconsent.min.js:1
e.runNextServiceOnError @ cookieconsent.min.js:1
e.onServiceResult @ cookieconsent.min.js:1
e.runServiceCallback @ cookieconsent.min.js:1
(anonymous) @ cookieconsent.min.js:1
function.s.onreadystatechange @ cookieconsent.min.js:1
XMLHttpRequest.send (async)
n @ cookieconsent.min.js:1
e.runService @ cookieconsent.min.js:1
e.locate @ cookieconsent.min.js:1
e.getCountryCode @ cookieconsent.min.js:1
e.initialise @ cookieconsent.min.js:1
(anonymous) @ (index):1
load (async)
(anonymous) @ (index):1
![ipinfo_error](https://user-images.githubusercontent.com/9217233/47258965-13993200-d471-11e8-8f02-00eecfe67c8a.png)

**Comment by relicmelex** [comment]
@DavidJMarcus Sorry for the long delay in reply. Is this still an issue for you or have you figured it out?

**Comment by DavidJMarcus** [comment]
This no  longer seems to be happening.
