### ISSUE TITLE
Silently accept after first visit if no action is taken?

### ISSUE THREAD

**Issue by brotherman1** [osano/cookieconsent#479]
I need the cookie bar to display on first page load, with the Accept and Decline buttons.
The first page load, should NOT enable any cookies - ony once the user accepts OR goes to the second page, without taking any action on the cookie banner.

If no action is taken, then the user silently accepts cookies, and has consented on the next page load, and the bar is hidden.
So, no action taken = accept button.

I am currently using "opt-out", and have tried using "dismissTimeOut" - but it does not have the decired effect.
setting it to 5000 (5 seconds), it accepts (which is okay), but if the user Declines cookies by clicking the button in the banner, goes to the next page, waits 5 seconds - then he silently has accepted cookies again somehow.

Any suggestions?

**Comment by aioobe** [comment]
Shouldn't `dismissOnWindowClick` do the trick? As soon as the user clicks a link to navigate to the next page, the banner is dismissed.
