### ISSUE TITLE
hide the notice (e.g. with an "X" in the top-right)

### ISSUE THREAD

**Issue by TheMangoTrain** [osano/cookieconsent#481]
Is there a way to get an "X" icon in the top-right, to allow users to simply hide the notice for that particular page session? When the user visits a new page, the consent prompt returns (as the user shall expect). This in no way has anything to do with the "Dismiss" button, which actually permanently hides the prompt (as the user shall expect).

Best thing I can think of doing is manually injecting a new element into the notice once it gets generated, but I'd like to avoid that work.

Is there a more practical way?

**Comment by TheMangoTrain** [comment]
Ok, figured it out.

Do a find for "close" on the [JS API page of the docs](https://cookieconsent.insites.com/documentation/javascript-api/). You'll find some properties related to HTML elements and layout. There's a built-in close element, to render it you have to define a layout that includes it.

Here's a sample code. With it you get an "X" in the top-right. However, this standard "X" will also invoke the "Dismiss" action, just like the "Dismiss" button. For me, it's undesired.

```
cookieconsent.initialise({
  layout: 'my-cool-layout',
  layouts: {
    'my-cool-layout': '<div class="my-cool-layout">\
      {{header}}{{message}}{{compliance}}</div>{{close}}',
  },

  content: {
    header: 'My awesome popup!'
  }
});
```

To get a hide-only "X", we need to create a new close element instance and appropriate function. The plugin doesn't seem to have an API function just to hide the notice.

Declare a layout, like earlier. Here we also define a new close element. It just has a brand new class `cc-customClose`.

   ```
    layout: 'my-cool-layout',
     layouts: {
       'my-cool-layout': '<div class="my-cool-layout">\
         {{header}}{{message}}{{compliance}}</div>{{close}}',
     },

  content: {
    header: 'My awesome popup!'
  }

 elements: {
  close: '<span aria-label="dismiss cookie message" tabindex="0" class="cc-customClose">{{close}}</span>',

},
```
Then we target that new close element and give it a basic hide action. I'm using WordPress, so jQuery is already loaded, so I'm just going to use jQuery for this:

```
$('.cc-customClose').on('click tap', function() {
      $(".cc-window[aria-label='cookieconsent']:first").hide();
});
```

You probably want to style the "X" this way too:

```
/* Top-right "X" close button */
.cc-customClose {
  position: absolute;
  top: 0;
  right: 0;
  cursor: pointer;
}

/* Hiding the main "Dismiss" button */
.cc-btn.cc-deny {
  display: none;
}
```

**Comment by TheMangoTrain** [comment]
Additionally:

The default "X" character is rendered with `&#x274c;` and for whatever reason, I'm unable to re-color this... it stays red. I have never seen this before. The character is unicode, and some fonts may not support it... is that the problem?

Anyways, there's other ways to render an "X", perhaps some more universal/normal than the above.

I'm now using utf8 `'&times;'` and it's working much more normal. Just had to double my font size.

See response [here](https://stackoverflow.com/a/28055057/4378314) and article [here](https://wesbos.com/times-html-entity-close-button/).

**Comment by ITPhoneHome** [comment]
This is interesting.  Could you provide more details to implement this?
Thanks

**Comment by relicmelex** [comment]
Closing issue from comment of:

> Ok, figured it out.

@TheMangoTrain Thanks for all the detail for others who stumble across this!
