### ISSUE TITLE
Disabling cookies script doesn't work on Chrome and Opera

### ISSUE THREAD

**Issue by Lachiave** [osano/cookieconsent#485]
I see that cookies are not disabled on Chrome and Opera. I have done a lot of tests. Everything works well on Firefox and Safari, but on Chrome and Opera cookies are not blocked. Why?

**Comment by easingthemes** [comment]
This script is not allowing or disabling cookies. There is no such a script. 
You need to control when cookies are set. 
This script gives you few methods which are triggered depending on your configuration and user action.
https://cookieconsent.insites.com/documentation/disabling-cookies/

So you need to change the logic of all your code / plugins which are setting cookies, and use them in combination with callbacks:

```
onInitialise: function (status) {
  var type = this.options.type;
  var didConsent = this.hasConsented();
  if (type == 'opt-in' && didConsent) {
    // enable cookies --> run all functions that are setting cookies, eg Google Analytics
  }
  if (type == 'opt-out' && !didConsent) {
    // disable cookies --> destroy all functionality that sets cookie and delete cookies
  }
},
onStatusChange: function(status, chosenBefore) {
  var type = this.options.type;
  var didConsent = this.hasConsented();
  if (type == 'opt-in' && didConsent) {
    // enable cookies
  }
  if (type == 'opt-out' && !didConsent) {
    // disable cookies
  }
},
```

**Comment by Lachiave** [comment]
Thank you for your answer, Dragan. Sure, I know it and I've already done
what you say, but, as I told you, it does not work on Chrome and Opera,
while it works great on Firefox and Safari. Check it out

Maria Silvana Radice
webmaster e webdesigner

Creazione di siti web amatoriali e professionali in *HTML5*.

Siti web personali:
Silvanasites <https://www.silvanasites.com>
La chiave nel pozzo <https://www.lachiavenelpozzo.com/>

Blog:
La chiave nel pozzo - il Blog
<https://lachiavenelpozzo-blog.blogspot.ch/?zx=8d78f8f7f1855b44>

Social network:
Facebook <https://www.facebook.com/lachiavenelpozzo/>
Google+
<https://plus.google.com/b/115746257038357710802/+Lachiavenelpozzo?hl=i>
Twitter <https://twitter.com/chiavenelpozzo>
Linkedin <https://www.linkedin.com/in/maria-silvana-radice-02414468>


*Informativa Privacy* - Ai sensi del D. Lgs n. 196/2003 (Codice Privacy) si
precisa che le informazioni contenute in questo messaggio sono riservate e
ad uso esclusivo del destinatario/i. Se lei non è il destinatario del
messaggio non è autorizzato a leggere, stampare, salvare o inoltrare ad
altri questo messaggio e gli eventuali allegati. Qualora il messaggio in
parola Le fosse pervenuto per errore, La preghiamo di eliminarlo senza
copiarlo, dandocene gentilmente comunicazione. Qualsiasi utilizzo di questo
messaggio da parte di persone diverse dai destinatari è proibito. Grazie.

*Privacy Information* - This message, for the D. Lgs n. 196/2003 (Privacy
Code), may contain confidential and/or privileged information. If you are
not the addressee or authorized to receive this for the addressee, you must
not use, copy, disclose or take any action based on this message or any
information herein. If you have received this message in error, please
advise the sender immediately by reply e-mail and delete this message.
Thank you for your cooperation.




Il giorno lun 3 dic 2018 alle ore 19:03 Dragan Filipović <
notifications@github.com> ha scritto:

**Comment by easingthemes** [comment]
What is not working?

**Comment by Lachiave** [comment]
I don't know, but if I go in page inspector, I see that cookies are locked in Firefox and are unlocked by clicking on consent, while if I do the same thing in Chrome, cookies are not blocked. Maybe I'm wrong with something in the configuration

**Comment by easingthemes** [comment]
Hey Lachiave, this is not related to this script. As I mentioned, this plugin is not working with cookies at all, it just give you a helper methods/events so you don't need to develop the whole popup logic.

But setting/deleting cookies in your app is totally on you.

**Comment by Lachiave** [comment]
Ok, thank you. After the holidays I study it better. Ciao

**Comment by relicmelex** [comment]
6+ Months without follow up. Assuming issues is resolved. Re-open with the following details if further assistance is required:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
