### ISSUE TITLE
GDPR & Google Analytics

### ISSUE THREAD

**Issue by evans111** [osano/cookieconsent#489]
I have been trying to stop cookies via Google Tag Manager, so that Google Analytics does not track any hits until the consent is given from my cookie bar. I am using the cookie created on Silktide and pasted it on WordPress in the Iubenda platform, so that I can have it dual language, depending on the site language.

This is my cookie bar script so far:

```
<!-- Begin Cookie Consent plugin by Silktide - http://silktide.com/cookieconsent -->
<script type="text/javascript">
    window.cookieconsent_options = {"message":"This website or its third-party tools use cookies, which are necessary to its functioning and required to achieve the purposes illustrated in the cookie policy. If you want to know more, please refer to the cookie policy. By clicking on 'Got it!' you agree to the use of cookies.","dismiss":"Got it!","learnMore":"Our Cookie Policy","link":"https://www.iubenda.com/privacy-policy/995663","theme":"light-bottom"};
</script>

<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.10/cookieconsent.min.js"></script>
<!-- End Cookie Consent plugin -->
```

I have read that disabling cookies should be done with the callback hook:

onInitialise: function (status) {
  var type = this.options.type;
  var didConsent = this.hasConsented();
  if (type == 'opt-in' && didConsent) {
    // enable cookies
  }
  if (type == 'opt-out' && !didConsent) {
    // disable cookies
  }
},
 
onStatusChange: function(status, chosenBefore) {
  var type = this.options.type;
  var didConsent = this.hasConsented();
  if (type == 'opt-in' && didConsent) {
    // enable cookies
  }
  if (type == 'opt-out' && !didConsent) {
    // disable cookies
  }
},
 
onRevokeChoice: function() {
  var type = this.options.type;
  if (type == 'opt-in') {
    // disable cookies
  }
  if (type == 'opt-out') {
    // enable cookies
  }
},

Where in my script do I put this though?

**Comment by jhabdas** [comment]
https://hackcabin.com/post/beyond-incognito/

**Comment by courtneyaschwartz** [comment]
@evans111  This is not the same repo as `silktide\cookieconsent` Silktide has old/deprecated code.

Your example callback hooks are for this new repo: https://cookieconsent.insites.com/documentation/disabling-cookies/

To use them:
1. Replace the old script. You can use this code generator to start: https://cookieconsent.insites.com/download/ and advanced options are here: https://cookieconsent.insites.com/documentation/javascript-api/
2. After your last setting, such as: `"content": { "dismiss": "Accept"}`
 add a comma, press Enter, then paste `onStatusChange:` and all other events you mentioned above. 
3. Replace each `//enable cookies` line with your Google Analytics function. Example: https://developers.google.com/analytics/devguides/collection/analyticsjs/ 
Also replace each `//disable cookies` following this example: https://developers.google.com/analytics/devguides/collection/analyticsjs/user-opt-out

**Comment by marcieee** [comment]
Hello, I have some difficulties to understand as well. Same problem as evans111, i don't know how to put together properly the script using tag manager. I tried this but it's not working properly
1) when first loading the website, the banner shows, and no cookies are loaded (this is correct)
2) When clicking "Allow cookies" a cookie named "cookieconsent_status" is loaded, but not ga cookies as _ga, _gid etc...
3) Only after clicking on revoke button, ga cookies are loaded.
So it does make sense, only revoking my permission to allow cookies, ga cookies are loaded!

The code used is the following, and I'm not sure is correct, I understand little Javascript.
It would be very useful if in Cookie Consent website would publish a full example for google analytics and Tag Manager.
Thank you for anyone helping me!
________
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" />
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-117938874-1"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>
<script>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#009de0",
      "text": "#ffffff"
    },
    "button": {
      "background": "#003f5c"
    }
  },
  "theme": "edgeless",
  "position": "top",
  "type": "opt-out",
  "content": {
    "message": "Questo sito o gli strumenti terzi da questo utilizzati si avvalgono di cookie necessari al funzionamento ed utili alle finalità illustrate nella nostra&nbsp;informativa sulla privacy.",
    "dismiss": "OK",
    "deny": "Rifiuta",
	"allow": "Accetta cookie",
    "link": "Privacy &amp; Cookie",
    "href": "http://www.siampl.it/privacy-e-cookie/",
	"policy": "Revoca"
  },
  onInitialise: function (status) {
 var type = this.options.type;
 var didConsent = this.hasConsented();
 if (type == 'opt-in' && didConsent) {
	// enable cookies 
  	window.dataLayer = window.dataLayer || [];
  	function gtag(){dataLayer.push(arguments);}
 	 gtag('js', new Date());
  	 gtag('config', 'UA-117938874-1');
 }
 if (type == 'opt-out' && !didConsent) {
   // disable cookies
   // Set to the same value as the web property used on the site
	var gaProperty = 'UA-117938874-1';

	// Disable tracking if the opt-out cookie exists.
	var disableStr = 'ga-disable-' + gaProperty;
	if (document.cookie.indexOf(disableStr + '=true') > -1) {
  	window[disableStr] = true;
	}

 }
},
onStatusChange: function(status, chosenBefore) {
 var type = this.options.type;
 var didConsent = this.hasConsented();
 if (type == 'opt-in' && didConsent) {
  // enable cookies 
  	window.dataLayer = window.dataLayer || [];
  	function gtag(){dataLayer.push(arguments);}
 	 gtag('js', new Date());
  	 gtag('config', 'UA-117938874-1');
 }
 if (type == 'opt-out' && !didConsent) {
  // disable cookies
   // Set to the same value as the web property used on the site
	var gaProperty = 'UA-117938874-1';

	// Disable tracking if the opt-out cookie exists.
	var disableStr = 'ga-disable-' + gaProperty;
	if (document.cookie.indexOf(disableStr + '=true') > -1) {
  	window[disableStr] = true;
	}
 }
},
onRevokeChoice: function() {
 var type = this.options.type;
 if (type == 'opt-in') {
  // disable cookies
   // Set to the same value as the web property used on the site
	var gaProperty = 'UA-117938874-1';

	// Disable tracking if the opt-out cookie exists.
	var disableStr = 'ga-disable-' + gaProperty;
	if (document.cookie.indexOf(disableStr + '=true') > -1) {
  	window[disableStr] = true;
	}
 }
 if (type == 'opt-out') {
  // enable cookies 
  	window.dataLayer = window.dataLayer || [];
  	function gtag(){dataLayer.push(arguments);}
 	 gtag('js', new Date());
  	 gtag('config', 'UA-117938874-1');
 }
}
})});
</script>
