### ISSUE TITLE
cookie.domain not being set for use across all subdomains

### ISSUE THREAD

**Issue by forcefulhandshake** [osano/cookieconsent#500]
After a user accepts the cookie usage alert on my site I am wanting cookieconsent to add a cookie to expire after 365 days and work across all subdomains but it is not working correctly.

If I only specify the expiry date it works fine but only on the subdomain it was set on (Host Only: true).
If I only specify the domain (.mydomain.com.au) it doesn't set a cookie at all.
If I specify the domain (.mydomain.com.au) and the expiry date it also doesn't set a cookie at all.

here is a code snippet..

```
window.addEventListener("load", function(){
  window.cookieconsent.initialise({
    cookie: {
      domain: ".mydomain.com.au",
      expiryDays: 365
    },
    palette:{
      popup: {background: "#999"},
      button: {background: "#aaa"},
    },
    content:{
      header: 'Cookies used on the website!',
      message: "my message...",
      dismiss: 'Accept',
      link: '',
      target: '_blank',
    }
  });
});
```

Any assistance would be much appreciated. I have read through other similar issues but none of the solutions work in my case

**Comment by relicmelex** [comment]
@forcefulhandshake With respect to [RFC6265](https://tools.ietf.org/html/rfc6265) most browsers should ignore that leading dot and allow top level domain access as well as subdomain access. This also holds true for cross sub-domains if you use the root domain without the dot. Give that a try and let me know if that was blocking it for you.

`domain: "mydomain.com.au",`

**Comment by relicmelex** [comment]
-- Update --
CookieConsent takes the value for the domain literally and applies it to the cookie, so how is handled becomes the responsibility of how your browser interprets cookies. I believe setting your domain without the `.` is the solution for you. See the following reverse stack trace to the `options.cookie` to see how your domain string is used directly:

```javascript
---
48:  setCookie: function(name, value, expiryDays, domain, path, secure) {
...
59:   cookie.push('domain=' + domain);
---
645: var c = this.options.cookie;
...
651: util.setCookie(
...
655: c.domain,
---
671: var c = this.options.cookie;
672: util.setCookie(c.name, '', -1, c.domain, c.path);
```
