### ISSUE TITLE
Config Generator - custom deny text

### ISSUE THREAD

**Issue by kshishkin** [osano/cookieconsent#505]
1. User enters the config generator page under https://cookieconsent.insites.com/download/
2. Chooses opt-in or opt-out compliance type
3. Provides custom text for dismiss button
4. The system generates js code with "dismiss" with the entered label as value.
5. The option should be "deny", as opt-in / out don't recognize "dismiss" label.

Please pardon if that's not the proper place to report the issue with the snippet generator.

**Comment by plinfut** [comment]
I face the same issue. The initialise => content => dismiss option has no effect.

**Comment by relicmelex** [comment]
@kshishkin and @plinfut 
There is a 'deny option' it just isn't in the configurator. Adding this is slated for the configurator, but for now you can add it yourself.

-EG-
```javascript
"content": {
    "deny": "No Cookies For Me!"
}
```

**Comment by godofdream** [comment]
this seems fixed in the configurator
