### ISSUE TITLE
header in content object is not displaying

### ISSUE THREAD

**Issue by texpatnyc** [osano/cookieconsent#507]
I'm using the following code, but the header is not showing up in the popup.  Has this been disabled or am I doing something wrong?

                <script>
			window.addEventListener("load", function(){
			window.cookieconsent.initialise({
				"palette": {
					"popup": {
						"background": "#0f2e77",
						"text": "#ffffff",
					},
					"button": {
						"background": "#8fdbcc",
						"text": "#ffffff"
					}
				},
				"theme": "classic",
				"position": "bottom-left",
				"content": {
					"header": "Privacy Policy",
					"message": "This site uses cookies to give you the best experience and to anonymously track site visits. For more information, please refer to our Cookies Policy.",
					"link": "Learn More",
					"href": "/public/CookiesPolicy.pdf"
				}
			})});
		</script>

**Comment by solettanitm** [comment]
It is not a defect, you should add "layout": "basic-header" in initialise to display header, the default layout is basic, so there is no header shown.

**Comment by relicmelex** [comment]
@texpatnyc As @solettanitm state, this is the intended effect, but you do need to change the layout to `layout: 'basic-header',`.

Cheers
