### ISSUE TITLE
blacklistPage option doesn't work

### ISSUE THREAD

**Issue by firelite** [osano/cookieconsent#509]
Hi,

I tried a couple of ways to blacklist my pages (domain.com/terms-of-use.html and domain.com/privacy-policy.html) so that cookie consent should not be showing. But neither seem to work.  Here's an example of how I tried to use the blacklistPage option:

```
<script>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#000"
    },
    "button": {
      "background": "#f1d600"
    }
  },
  "position": "bottom-right",
   behavior: {
       blacklistPage : ['/terms-of-use.html', '/privacy-policy.html']
    },
    blacklistPage : ['/terms-of-use.html', '/privacy-policy.html'],
  })
});
</script>
```

Is it a bug?  Or am I just using this incorrectly?

Thanks.

**Comment by relicmelex** [comment]
@firelite Did you get this figured out, or do you still need assistance?

For reference it's:
```javascript
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  palette:{
    //...,
  blacklistPage: [ '/terms-of-use.html' ]
})});
```

**Comment by relicmelex** [comment]
Stale. Closing issue. If this comes back up please open a new issue in the 'bug' category as it will ask you for more detail to help us better resolve the issue.
