### ISSUE TITLE
Add support for cookie types

### ISSUE THREAD

**Issue by filips123** [osano/cookieconsent#516]
There should be support to allow specific cookies types.

When displaying consent, there should be button "Configure" or "Details" that would open popup with more details and cookie types. Users should then be able to allow only specific types of cookies.

Maybe there could also be all cookies displayed, with there type and description. This could maybe be automatically set or provided by developer of website.

This types should be:

* **Necessary**: Cookies that are necessary and not used for tracking. Consent should not be given for them.
* **Preferences** or **Functionality**: Cookies for saving preferences or user login. Consent may be given for them.
* **Statistics** or **Analytics**: For statistics and analytics.
**Marketing**: For tracking of users for marketing.

**Comment by arlogilbert** [comment]
Related to #556

**Comment by relicmelex** [comment]
Moved and close:[ Comment on 556](https://github.com/osano/cookieconsent/issues/556#issuecomment-513586124)
