### ISSUE TITLE
Romania is not showing cookie law

### ISSUE THREAD

**Issue by EpicStephen** [osano/cookieconsent#519]
Hello,

I know you guys had some issues opened about Romania not showing cookie law, and from what I've seen you guys updated it in 2017 or 2018? Problem is that with "location: true", and with a Romanian IP, I don't see the cookie bar, and I should see it since it's an EU country.  

Any ideas why it's not showing up? Tested with a VPN a bunch of EU countries like DE, CZ, SE, UK, IT, FR etc... all working as expected with location:true, but not romania.

Thanks,
Stephen

**Comment by drgluk** [comment]
Hi, I can't help with your problem but could you let me know how you even setup geo location? I have this code 

<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>
<script>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#000"
    },
    "button": {
      "background": "#f1d600"
    }
  },
  "position": "bottom-left"
})});
</script>


But I'm not sure how to setup geo targetting? Thanks

**Comment by EpicStephen** [comment]
Hi, I have it like this: 

`<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>
<script>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#edeff5",
      "text": "#838391"
    },
    "button": {
      "background": "#4b81e8"
    }
  },
	
"location": "true",
	
  "content": {
    "href": "https://example.com/privacy/"
  }

})});
</script>`

Hope this helps.

Still, can someone maybe answer my OP question?

**Comment by gssaditya** [comment]
I think you have to host js on your server and Put 'RO' in the list manually.

**Comment by gssaditya** [comment]
I've tried it it works!

**Comment by drgluk** [comment]
> 
> 
> Hi, I have it like this:
> <script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script> <script> window.addEventListener("load", function(){ window.cookieconsent.initialise({ "palette": { "popup": { "background": "#edeff5", "text": "#838391" }, "button": { "background": "#4b81e8" } },
> 
> "location": "true",
> 
> "content": {
> "href": "https://example.com/privacy/"
> }
> 
> })});
> </script>
> 
> Hope this helps.
> 
> Still, can someone maybe answer my OP question?

Great, thanks!
