### ISSUE TITLE
Show only once?

### ISSUE THREAD

**Issue by soyjuanmedina** [osano/cookieconsent#523]
I use in my site your cookie consent, by always I reload I see the bar even though I click on the ok button.... but I see the same occurs in the demo site 

https://cookieconsent.insites.com/download/  

How can only show once?

**Comment by courtneyaschwartz** [comment]
@soyjuanmedina Your issue doesn't have enough info to answer the question. However, normally that doesn't happen for me.
Does your browser or plugins block the `cookieconsent_status` cookie...? If that happens, then of course it is impossible for CC to remember your choice, and it will always show again during next page load.

**Comment by soyjuanmedina** [comment]
Thanks a lot @courtneyaschwartz , then is problem of my browser? you only see the bar in the demo site only once?

**Comment by courtneyaschwartz** [comment]
On the download (script generator) page, it's not the same. That bar is not "real" -- its purpose is just to show settings changes. If you click "Got it!" it doesn't matter. It will ignore the cookie and pop up every time you try a new position, layout, etc.

On most normal "real" sites,  or this demo:
https://cookieconsent.insites.com/app/themes/insites-cookie-consent/examples/example-7-javascript-api.html
if you dismiss the bar, it does _not_ appear again unless cookies expire, or you delete/block them. 

So if your _real_ site can't "remember", then checking your browser is a good place to start. Plugins, Incognito/Private mode, and cookie blockers are the most common reasons.

**Comment by soyjuanmedina** [comment]
Ah, ok... but by default, if I do not specify anything when the cookie expires?... maybe this is the problem, I don't specify anything and the cookie expires at the end of the session.

**Comment by courtneyaschwartz** [comment]
I'd have to see your config to answer that.

But if you didn't change the defaults, no. It's 365 days.
https://cookieconsent.insites.com/documentation/javascript-api/#cookie_options

**Comment by soyjuanmedina** [comment]
Uppsssss... then I don't know... I can't show you my config because finally I use other library (https://github.com/andreasonny83/angular2-cookie-law) and I have the same issue and I solve specifaying the cookie expires, thats why I thought this was the problem.....
