### ISSUE TITLE
Deferring loading of cookie warning?

### ISSUE THREAD

**Issue by GiacomoLaw** [osano/cookieconsent#525]
https://giacomolaw.me/blog/2019/03/deferring-css-js/

When I do this, the script does not load. How can I fix this?

Thanks

**Comment by courtneyaschwartz** [comment]
@GiacomoLaw Normally the cookie consent dialog is initialized and attached during the page's `onLoad()` event. If you're deferring scripts, by definition they won't be loaded when that event fires. You may need to manually attach and initialize.

**Comment by GiacomoLaw** [comment]
Great, thanks.
