### ISSUE TITLE
No cross-reference of source repo from main website

### ISSUE THREAD

**Issue by Cliabhach** [osano/cookieconsent#526]
If a website offers a free and open source project, it should also provide a way to obtain the source code for that project. Please add a link to this github repository to https://cookieconsent.insites.com/ and/or https://cookiesandyou.com/

**Comment by courtneyaschwartz** [comment]
@Cliabhach It already does... Click the "Source code" button on the right side of this page: https://cookieconsent.insites.com/documentation/about-cookie-consent/

**Comment by Cliabhach** [comment]
Oh wow, that's really hidden. Can't it go on the front page, next to the version number?

**Comment by courtneyaschwartz** [comment]
A GitHub icon could probably make it easier to notice. I didn't catch it at first either.
