### ISSUE TITLE
Can I use multiple popups? One for cookie, one for privacy?

### ISSUE THREAD

**Issue by solarsilk** [osano/cookieconsent#535]
I want to use this script to do the normal cookie consent, but additionally, on the same domain, to notify users of new privacy policy changes and get their consent. I tried using the cookie name to name each differently, but the one seems to overwrite the other. 

Can this script be used for 2 different cookies at the same time on the same domain? Thanks.

**Comment by wargo32** [comment]
Users do not allow any popups
