### ISSUE TITLE
revoke function

### ISSUE THREAD

**Issue by fine-G** [osano/cookieconsent#540]
how can I call the revoke function by jQuery / JS?
I need an option that I can place at a custom place in the content.

for example in the footer "change my cookie settings" that shows up the banner again an the user can change the options. 
or for example direct at a website part/function that needs cookies

**Comment by relicmelex** [comment]
@fine-G Thank you for trying to articulate your need. Unfortunately I don't follow very well...

Are you saying something other than the built-in callback: `onRevokeChoice`?
This can be set in the config options and is called as part of CookieConsent's lifecycle callbacks.

Please see our [JavaScriptAPI](https://cookieconsent.osano.com/documentation/javascript-api/)
( It's at the bottom )

**Comment by relicmelex** [comment]
Stale. Closing issue. If this comes back up please open a new issue in the 'bug' category as it will ask you for more detail to help us better resolve the issue.
