### ISSUE TITLE
Revoke button doesn't get the theme name

### ISSUE THREAD

**Issue by bencergazda** [osano/cookieconsent#543]
**Describe the bug**
Revoke button doesn't get the name of the custom theme as a CSS class.

**To Reproduce**
1. Initialise the cookie consent in opt-in mode with a custom theme name 'test-theme'
```window.cookieconsent.initialise({ theme: 'test' });```
2. Cookie consent appears, it has a CSS class referring to the custom theme `cc-theme-test`
3. Accept the consent
4. the small 'Cookie Policy' revoke button appears
5. The  `div.cc-revoke` element won't have the `cc-theme-test` CSS class, as it should (in my opinion)

**Expected behavior**
The  `div.cc-revoke` element should have the same CSS class referring to the custom theme name as the `div.cc-window` does.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Firefox
 - Version: 67

**Comment by relicmelex** [comment]
@bencergazda Thank you for your report. Apologies on the delayed reply we're just getting back to active support. I should have an update on this for you soon.

**Comment by relicmelex** [comment]
Above PR resolves this issue.

@bencergazda The next release will see this resolution.

**Comment by bencergazda** [comment]
@hodonsky @arlogilbert Hi, thanks for resolving this. Are you going to release a new version in the near future?
