### ISSUE TITLE
GA cookies to show regardless of consent

### ISSUE THREAD

**Issue by olomouc** [osano/cookieconsent#544]
I am working on a Drupal site where someone has developed a custom module that uses the cookieconsent js. I have been asked to look at an issue where they are reporting that the google analytics cookies are only set upon consent but would like/expect them to show on page load irrespective of consent. I think this would be default behaviour that they are not set and that they are set on consent but is there a way to change this or is it not important because analytics doesnt need the cookies to transmit data back?

**Comment by arlogilbert** [comment]
You would need to take the GA code that is provided by Google and wrap that inside the consent handler for the CC code. That way until the consumer consents to cookies the GA code will not fire and load the scripts.
