### ISSUE TITLE
How to implement geo ip cookie consent code into website?

### ISSUE THREAD

**Issue by gssaditya** [osano/cookieconsent#545]
I just want to show the banner in the EU. how do i implement that?
Is there code for actual geo detection?
Please help
Thanks.

**Comment by gssaditya** [comment]
I am using Cloudflare

**Comment by gssaditya** [comment]
by default(when i just copy and paste the code) all countries see the consent popup. I want to change that.

**Comment by gssaditya** [comment]
I figured it out.

**Comment by webdevpchoi** [comment]
@gssaditya 
What did you do to get it to work in just the EU?
