### ISSUE TITLE
A simpler version of js. For those who just want a popup(with text and link) with geo location.

### ISSUE THREAD

**Issue by gssaditya** [osano/cookieconsent#546]
I think a simpler version with less js would be a really good option for those who just want a small popup.
This would also decrease load times.
A clean small js code with popup and Geo location.
This would be a great option for a lot of people(i think).

**Comment by arlogilbert** [comment]
The javascript is 146 Bytes making it an extremely small library with very little code & the implementation script is a few lines of copy & paste code into the HTML document.
