### ISSUE TITLE
window.cookieconsent SOMETIMES is not defined

### ISSUE THREAD

**Issue by TomasRup** [osano/cookieconsent#547]
**Describe the bug**
Sometimes I am getting `window.cookieconsent` as undefined after I'm trying to access it after `load` event.

**To Reproduce**
```html
<head>
  <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.css" />
  <script src="//cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.js"></script>
</head>
<body>
  <script>
        const loadCookieConsent = () => {
          const { cookieconsent } = window;
          if (!cookieconsent) {
            throw new Error('Error!!!!!!'); // This should never happen in this scenario
          }
        };

        window.addEventListener('load', () => loadCookieConsent());
  </script>
</body>
```

**Expected behavior**
`window.cookieconsent` to be defined for 100% of use cases.

**Desktop (please complete the following information):**
It happened to ~1% of my users (80 visitors out of 10000 got it) and it happened on very different oses/browsers:
- windows 10 / chrome
- android / chrome
- windows 7 / uc browser
- windows 10 / opera
- android / "samsung internet"
- etc.

**Comment by arlogilbert** [comment]
We are unable to replicate this bug @TomasRup.

There are numerous plugins that block cookie popups similar to the way that an ad blocker may block popups, these types of plugins would block the script from loading.

One way to test is to host the JS on your own site with a file name that is generic (e.g. script_c.js) and then see if the error persists.

Given that we can not replicate I'm closing this issue. If you are able to provide additional guidance or a live site where you are seeing the error we would be happy to investigate further.
