### ISSUE TITLE
Cookies consent does not show

### ISSUE THREAD

**Issue by toplisek** [osano/cookieconsent#551]
I have tested cookies consent but it will not be shown when I use almost identical demo version. Is there any added script to execute code?
Can I send you an email?

**Comment by arlogilbert** [comment]
If you provide a link to the site that is having the problem we can take a look at it, but this is an open source product and we generally don't provide much technical support.

**Comment by toplisek** [comment]
Due to security, it is not possible. Please find HTML:
`<!DOCTYPE HTML>

<html>

<head>
  <title>Osano</title>

<link rel="stylesheet" type="text/css" href="cookieconsent-min.css" />
<script type="text/javascript" src="mycookies1.js"></script>
<script>
window.addEventListener("load", function()
 {
  window.cookieconsent.initialise(
   {
   "palette": {
    "popup": {
     "background": "#edeff5",
     "text": "#838391"
     },
    "button": {
     "background": "#4b81e8"
     }
    },
   "content": {
    "showLink": true,
    "position": "top",
    "static": true,
    "message": "Cookies text",
    "dismiss": "Finally good",
    "link": "More info about policy",
    "href": "XXX.html"
    }
   }
  )
 }
);
</script>
</head>

<body>

</body>

</html>`

**Comment by toplisek** [comment]
Source: 
<link href="build/cookieconsent.min.css" rel="stylesheet">
<script src="build/cookieconsent.min.js"></script>
