### ISSUE TITLE
Installed code as per front screen of your website but no configurator appears

### ISSUE THREAD

**Issue by peterjdickinson** [osano/cookieconsent#552]
**Describe the bug**
Installed code as per front screen of your website but no configurator appears and so it says site uses Cookies (like it does on your site but I can't choose which cookies to use)

**To Reproduce**
1. Go to your website or kubstaging2.kub-uk.net
2. Both display that the site uses Cookies but I can't select which ones to use

**Expected behavior**
When I installed the code in the header I expected some configurator to appear which I could setup. I went to your website and clicked on the link to the wizard configurator and that took me to the home page again where the code is.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac and Windows
 - Browser Chrome/Edge/Safari

**Smartphone (please complete the following information):**

**Additional context**
I am clearly missing something but I can't see what and your documentation doesn't seem to be working

**Comment by rv-solutions** [comment]
For current version this as expected. There is no configurator built in. Maybe in a future version...

**Comment by relicmelex** [comment]
@peterjdickinson Thank you for reporting this issue. The configurator or 'wizard' generates a block of code for you to copy paste directly into your html file, but is not packaged with CookieConsent to keep the package size as small as possible.

Please find the configurator here: https://cookieconsent.osano.com/download/
