### ISSUE TITLE
window.cookie.initialise is not a function

### ISSUE THREAD

**Issue by rokasma** [osano/cookieconsent#553]
Laravel Framework: 5.8.24
PHP Version: 7.2.19

**Describe the bug**
Cookieconsent not working installed via npm.

I installed cookieconsent with npm and included in my project ( main app.js ) :
`window.cookieconsent = require('cookieconsent');`

And at bottom wrote this code:
```
window.addEventListener('load', function(){
        window.cookieconsent.initialise({
          "palette": {
            "popup": {
              "background": "#3c3c3c"
            },
            "button": {
              "background": "#21859e"
            }
          },
          "position": "bottom-left",
          "content": {
            "message": "Informuojame, kad šioje svetainėje naudojami slapukai (angl. Cookies). Sutikdami, paspauskite ,,Sutinku” arba naršykite toliau.",
            "dismiss": "Sutinku",
            "link": "Plačiau",
            "href": "/privatumo-politika"
          }
        })
    });
```

In console I always get `window.cookieconsent.initialise` is not a function.

But if I load your JS via CDN, it works perfectly. Any suggestions?

**Comment by arlogilbert** [comment]
Requiring a javascript on the client side is not the same as requiring in a node project.

The correct way to implement cookie consent when you build via NPM is to add a `<script>` tag with an src to the `build/cookieconsent.min.js` file. From the way you describe your use case, I don't see a real benefit to loading the NPM copy versus loading the CDN copy. With the CDN version, you will get non-breaking fixes automatically whereas with NPM you have to keep your code up to date.

Generally, people use the NPM version when they want to compile the script into a single script file along with all of their other client-side code.

If however you absolutely must use the `require` format then I would recommend looking at one of the numerous libraries that add require capabilities to client-side scripts such as [Browserify](http://browserify.org/) although be forewarned that this now adds additional weight/load-time to your page.
