### ISSUE TITLE
Optional callback to remote URL on consent change

### ISSUE THREAD

**Issue by arlogilbert** [osano/cookieconsent#555]
If the end user accepts consent, make a call back to a defined URL that allows the Cookie Consent developer to record the opt-out

**Comment by relicmelex** [comment]
@arlogilbert I believe the developer should just use the `onStatusChange` callback and make their own API request with their application. Keeping our plugin decoupled from their application logic is the ideal setup. It also allows for the most flexibility.

**Comment by arlogilbert** [comment]
Sounds good to me.
