### ISSUE TITLE
Cookie Categorization and category opt-out

### ISSUE THREAD

**Issue by arlogilbert** [osano/cookieconsent#556]
There should be a modal dialog that reads all cookies currently in the browser ( on a domain ) and display them by category. If the category is unknown it should go into a special "Uncategorized" category which also allows opt-out.

Categories:
- [x] Necessary / Essential
- [x] Preferences / Functionality (Personalization)
- [x] Statistics / Analytics
- [x] Marketing
- [x] Uncategorized

View Layer:
- [x] Display: The cookie categories with selection capability
- [x] Essential Cookie: Always selected.
- [x] Display: Allow users to toggle their acceptance by category

Other Deliverables:
- [x] Opt-In/Opt-Out per category ( store / revokable )
- [x] Destroy cookies on Opt-Out of category
- [x] Attach the 'type' cookie to domain & check on start-up w/ config so if that ever changes it can change the rule set it follows.

**Comment by relicmelex** [comment]
Comment from [516](https://github.com/osano/cookieconsent/issues/516#issue-416513575)
> There should be support to allow specific cookies types.
> 
> When displaying consent, there should be button "Configure" or "Details" that would open popup with more details and cookie types. Users should then be able to allow only specific types of cookies.
> 
> Maybe there could also be all cookies displayed, with there type and description. This could maybe be automatically set or provided by developer of website.
> 
> This types should be:
> 
> - **Necessary**: Cookies that are necessary and not used for tracking. Consent should not be given for them.
> - **Preferences** or **Functionality**: Cookies for saving preferences or user login. Consent may be given for them.
> - **Statistics** or *Analytics*: For statistics and analytics.
> - **Marketing**: For tracking of users for marketing.

**Comment by relicmelex** [comment]
Moved requirement from #559 because this is all one related task, with some smaller parts.

**Comment by relicmelex** [comment]
Moved in requirement from #560 As it's related.

**Comment by daniel-mannheimer** [comment]
Hi guys, thanks for this great Cookie solution.
As of the latest EuGH adjudgement I stumbled upon this issue and tried to find an example for categories usage.
Is there any documentation coming?

**Comment by Donsky-Osano** [comment]
@daniel-mannheimer Great timing... We're releasing this as v4.X soon and the documentation on the website will reflect these changes.

If you checkout the 'dev' branch right now it's all available. There may be some hints in the README.md and the CHANGELOG.md in that branch but as it stands we haven't pushed v4 into LTS yet.

Look for us on the TechCrunch stage in the next couple days for our enterprise product too Consent Manager - By Osano. It also handles script management as well to bring all web portals up to complete compliance with a single drop in line `<script></script>` tag

**Comment by daniel-mannheimer** [comment]
@Donsky-Osano Thanks for the prompt reply. Had a quick look after installing dev, but usage is not quite obvious (to me). Looking forward to the release/documentation and best wishes for TechCrunch ;)

**Comment by danfwdmotion** [comment]
@Donsky-Osano Hi, how far off is category handling from release?
