### ISSUE TITLE
How to change text color of "Learn more" ?

### ISSUE THREAD

**Issue by raj303** [osano/cookieconsent#574]
How to change the text colour of "Learn more"?

**Comment by relicmelex** [comment]
@raj303 Use CSS, the library has no direct target or option on that link for styling other than a class `cc-link`. Which is what I recommend you use for targeting.

**Comment by relicmelex** [comment]
In the pallet of the options, see below:

```javascript
window.cookieconsent.initialise({
  //...
  palette: {
    popup: {link: '#FFFFFF'}
  }
})
```

https://cookieconsent.osano.com/documentation/javascript-api/ 

Scroll down to 'Palette options'
