### ISSUE TITLE
Remove Banner from Shopify Site

### ISSUE THREAD

**Issue by nycelisting** [osano/cookieconsent#577]
Hello - 

I installed your banner plug in from the shopify app store about a year ago.

Now that it is unsupported app I would like to remove it from my site.

I deleted the app, but code was not removed.

Please provide documentation on how to remove the old silktide.com banner code without disrupting the site.

Thank you!

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by relicmelex** [comment]
@nycelisting Unfortunately since we are part of shopify or their application setup process, and don't have access to how they configure their applications we cannot advise you on how to do this. Shopify support should have the answer for you for all things Shopify.
