### ISSUE TITLE
Cookie Consent Question 

### ISSUE THREAD

**Issue by reesadigital** [osano/cookieconsent#604]
Hi, 

This is not quite a feature request but it's something I'd like to understand more.

My understanding is Google Analytics, for instance, starts collecting data from the user before the user gets to read the banner letting them know about the use of cookies.  Is this correct? Or if users opt-out, Google Analytics will remove the record of user? 

I'd be grateful if you could clarify how the above work. 

Many thanks

Risa

**Comment by Donsky-Osano** [comment]
This depends on your setup, this could be true, and this could be not true... If you're looking for something to comply with the new consent laws with something that will prevent script execution until consent is allowed, please look into the coming soon: Osano - Consent Manager
