### ISSUE TITLE
Secure Cookie Flag

### ISSUE THREAD

**Issue by smartey** [osano/cookieconsent#605]
Is it true that this project sets cookies without setting a security flag in case HTTPS is in use? According to "https://www.immuniweb.com/" my website has a small issue; "Cookies with potentially sensitive information are sent without secure flag". After checking I noticed that of the 3 cookies my website sets the only one not being Secure is cookieconsent.

**Comment by Donsky-Osano** [comment]
@smartey please see: https://cookieconsent.osano.com/documentation/javascript-api/

There is a 'secure' flag on the 'cookies' object in the options settings. Set this to true and the secure flag will be added to your cookie_consent_cookies, you will have to add it to any cookie you create. CookieConsent as a plugin is only set to manage consent, not all of the cookies. If you're looking for a product to do just that, please look into the coming soon: Osano - Consent Manager

Cheers!

**Comment by smartey** [comment]
Hi and thank you, I am on older version and should have checken docs(!). Thanks for your reply.
