### ISSUE TITLE
Both Cookie Buttons firing the same action?

### ISSUE THREAD

**Issue by saldu** [osano/cookieconsent#613]
I am a beginner trying to get the script working but it appears that, using the op-out method from the autogenerated code, pressing either button leads to the same result.
Here is the code I currently have:
(the "true2" message is shown both when pressing the Accept and Reject button)
Could it be that the variable only stores whether a button was pressed, but not which one? Is there a correct one? How do I check the pressed button?

```
<script src="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.js" data-cfasync="false"></script>
<script>
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#eb6c44",
      "text": "#ffffff"
    },
    "button": {
      "background": "#f5d948"
    }
  },
  "type": "opt-out",
  "content": {
    "message": "Diese Website verwendet Cookies, um Ihnen die bestmögliche Nutzererfahrung zu bieten.",
    "dismiss": "Cookies erlauben",
    "allow": "Cookies erlauben",
    "deny": "Cookies blockieren",
    "link": "Weitere Informationen",
    "href": "link to my data privacy site"
  },
  onInitialise: function (status) {
 var type = this.options.type;
 var didConsent = this.hasConsented();
 if (type == 'opt-out' && !didConsent) {
  document.cookie = '_ga_opt_out=true; expires= Thu, 31 Dec 2099 23:59:59 UTC; path=/';
  window['ga-disable-UA-XXX-X'] = true;
      alert("true1");
 }
},
onStatusChange: function(status, chosenBefore) {
 var type = this.options.type;
 var didConsent = this.hasConsented();
 if (type == 'opt-out' && !didConsent) {
  document.cookie = '_ga_opt_out=true; expires= Thu, 31 Dec 2099 23:59:59 UTC; path=/';
  window['ga-disable-UA-XXX-X'] = true;
      alert("true2");
 }
},
onRevokeChoice: function() {
 var type = this.options.type;
 if (type == 'opt-out') {
  document.cookie = '_ga_opt_out=false; expires= Thu, 31 Dec 2099 23:59:59 UTC; path=/';
  window['ga-disable-UA-XXX-X'] = false;
    alert("true3");
 }
},
  
});


</script>
```

**Comment by saldu** [comment]
I solved it.

It happened because the "didConsent" does not save the choice of button. It just saves whether any button was pressed.

The documentation of the callback loop should be adjusted accordingly.
You need to check for the "status" flag to make it work, which saves the pressed button.

**Comment by johnnydevs** [comment]
> I solved it.
> 
> It happened because the "didConsent" does not save the choice of button. It just saves whether any button was pressed.
> 
> The documentation of the callback loop should be adjusted accordingly.
> You need to check for the "status" flag to make it work, which saves the pressed button.

Any change you could show us some working code please? Having the same issue! Thanks
