### ISSUE TITLE
How to use opt-in and opt-out at same time

### ISSUE THREAD

**Issue by bobi33** [osano/cookieconsent#634]
I cannot seem to determine a way to use the opt in and opt out features at the same time. For example, automatically have anonymized google analytics tracking code turned on when user is on the site and this an opt out feature, and at the same time having an opt in feature for more personalized cookies that track personally identifiable information. 

Any ideas?

**Comment by arlogilbert** [comment]
Hi, @bobi33 you can use the develop branch which has support for categories.

Alternatively, you can use our hosted version which automatically does exactly what you're asking for. You can learn more about that at [https://www.osano.com/features/consent-management](https://www.osano.com/features/consent-management)
