### ISSUE TITLE
How to use the checkboxes

### ISSUE THREAD

**Issue by Nesfiran** [osano/cookieconsent#689]
Hello,

how to use the checkboxes (Marketing/ Personalization/ Analysis) on the Osano page in the CookieConsents plugin?

Unfortunately you can't find anything about this in the settings and in the API description.

Greetings

**Comment by sgoldenb** [comment]
If you use the current dev version you can use the type 'compliance'

The docs seem to be a few versions behind and are not that comprehensive to begin with.

Have a look at https://github.com/osano/cookieconsent/blob/dev/src/options/popup.js for all the options.

**Comment by Nesfiran** [comment]
Thank you very much for the information, it helped me a lot.

**Comment by molerat619** [comment]
How did you get it to work in the end? I can only see that we can use the `categories` type, but where do we define the categories? It doesn't work for me.

**Comment by Nesfiran** [comment]
Using the category type is apparently also the right solution.
I have defined the categories myself look into **categories.map( ( category, index ) => ...**

**Comment by molerat619** [comment]
@Nesfiran thanks. How do you define the categories? Obviously the variable is not defined and what is the structure even supposed to look like? Help is much appreciated.

**Comment by Nesfiran** [comment]
Please see the link posted above starting at line 62 for all possible options.
You initialize the script as follows, from here on you can define all variables yourself.

const cc = new CC({
  //...options,
  type   : "categories"
})

For example: 
const categories = [Category 1, Category 2, Category 3];
